acmx_website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('projects.urls', namespace='projects')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

projects/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from projects import views

urlpatterns = patterns('',
    # Template views.
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    #url(r'^$', TemplateView.as_view(template_name='projects/index.html'),
     #   name='index'),
    url(r'^about$', TemplateView.as_view(template_name='projects/about.html'),
        name='about'),
    url(r'^contact$', TemplateView.as_view(template_name='projects/contact.html'),
        name='contact'),
    # Project views.
    url(r'^p/(?P<slug>[\w-]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^p/(?P<slug>[\w-]+)/edit$', views.ProjectEditView.as_view(), name='edit'),
    url(r'^p/new$', views.ProjectCreateView.as_view(), name='create'),
)

projects/models.py
from django.db import models
from django.utils.text import slugify

class UserProfile(models.Model):
    pass

class Project(models.Model):
    slug = models.SlugField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    long_description = models.TextField()
    link = models.CharField(max_length=200)
    image = models.ImageField()
    contributors = models.CharField(max_length=200)
    languages = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', auto_now=True,
            auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Project, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

projects/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.utils.decorators import method_decorator
from django.views import generic
from django.utils import timezone

import markdown

from projects.models import Project, UserProfile


class DetailView(generic.DetailView):
    model = Project
    template_name = 'projects/project.html'

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        context['details'] = markdown.markdown(self.object.long_description,
                                               safe_mode='remove')
        return context

class IndexView(generic.list.ListView):
    model = Project
    template_name = 'projects/index.html'
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class ProjectEditView(generic.edit.UpdateView):
    model = Project
    template_name = 'projects/project_edit.html'
    fields = ['title', 'description', 'long_description', 'link',
              'contributors', 'languages', 'image']

    def get_success_url(self):
        # TODO: Is this safe?
        return reverse('projects:detail',
                       kwargs={'slug': slugify(self.request.POST['title'])})

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectEditView, self).dispatch(*args, **kwargs)


class ProjectCreateView(generic.edit.CreateView):
    model = Project
    template_name = 'projects/project_create.html'
    fields = ['title', 'description', 'long_description', 'link',
              'contributors', 'languages', 'image']

    def get_success_url(self):
        # TODO: Is this safe?
        return reverse('projects:detail',
                       kwargs={'slug': slugify(self.request.POST['title'])})

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreateView, self).dispatch(*args, **kwargs)

projects/templates/projects/about.html
{% extends "projects/base.html" %}
{% load staticfiles %}
{% block title %}About | ACMx Labs{% endblock %}
{% block content %}
  <div class="slider">
    <div class="welcome">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-offset-2 col-md-5">
            <h1>About ACMx</h1>
          </div>

          <div class="col-md-3">
            <p><strong>President:</strong>&nbsp;<a href="mailto:shamrick@mymail.mines.edu">Steve Hamrick</a></p>
            <p><strong>Vice President:</strong>&nbsp;<a href="mailto:vkadiris@mymail.mines.edu">Vishnu Kadirisani</a></p>
            <p><strong>Secretary:</strong>&nbsp;<a href="mailto:nttran@mymail.mines.edu">Nhan Tran</a></p>
            <p><strong>Treasurer:</strong>&nbsp;<a href="mailto:achampio@mymail.mines.edu">Alan Champion</a></p>
          </div>
        </div><br>

        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <p>ACMx is the student branch of the Association for Computing Machinery at the Colorado School of Mines. Alongside the separate branch of ACM-W, we are a group specifically dedicated to building technical projects to benefit the student body, funded by the group budget and donations. We also work together with a variety of organizations in outreach programs throughout the community.</p>
            <p>For those interested in joining ACMx, membership is completely free, and attendance is not mandatory. It's not a class, it's not a research project. There are no grades, there are no teachers, and there are no tests. Instead, we work to our own schedules under our own leadership. If you want to get things done, then it's up to you to work with your team on your project. </p>
            <p>Meetings are held once a week on campus when school is in session. Typically, we get together for around 90 minutes each meeting to plan events, get updates on projects, and get to work! To meet our own deadlines and accomplish our own goals, groups often meet individually for longer periods to just work on their projects. Currently, we meet at <b>6 pm every Tuesday in BB 316A.</b></p>
            <p>We are a devoted group of individual students from all class levels, all backgrounds, and all experience levels. Whether you're a novice programmer looking to get experience, an experienced programmer looking to hone their development skills, or even just someone looking to meet new people, come to a meeting and start helping the student body! If you're interested in learning more about the club, check out the project pages on this site, or join the mailing list.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

projects/templates/projects/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-US">
<head>
  <link rel="icon" href="{% static 'projects/icon.png' %}" />
  <!-- stylesheets -->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://bootflat.github.io/bootflat/css/bootflat.css" />
  <link rel="stylesheet" type="text/css" href="{% static 'projects/style.css' %}" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <!-- jQuery -->
  {% block extra_includes %}{% endblock %}
  <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>  
  <script>
    $(function() {
        $("#accordion").accordion({
            collapsible: true
        });
    });
  </script>
  <title>{% block title %}ACMx Labs{% endblock %}</title>
</head>
<body>
  <div id="main">
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    {% block header %}
      <div class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="{% url 'projects:index' %}" class="">
            <img id="logo" src="{% static 'projects/acmx.png' %}" alt="ACMx" />
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <form class="navbar-form">
                <div class="input-group form-search search-only">
                  <input type="text" class="form-control search-query"
                      placeholder="Search" />
                  <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                  </div>
                </div>
              </form>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'projects:about' %}">about</a></li>
            <li><a href="{% url 'projects:contact' %}">contact</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'projects:create' %}" data-placement="bottom" data-toggle="tooltip" type="button" data-original-title="new project">
                <i class="glyphicon glyphicon-plus"></i></a></li>
             <li><a data-toggle="modal" data-target="#logoutModal" data-placement="bottom" data-toggle="tooltip" type="button" data-original-title="log out" id="tooltip">
                <i class="glyphicon glyphicon-log-out"></i></a></li>
          {% else %}
            <li><a class="btn btn-default" href="{% url 'google_login' %}">sign in</a></li>
          {% endif %}
          </ul>
        </div>
      </div>
    {% endblock %}
    </nav>
  
    <div id="content">
      {% block content %}
        <!-- Main page content goes here -->
      {% endblock %}
    </div>
  
  <div class="footer">
    <div class="container-fluid col-md-8 col-md-offset-2">
      <div class="row">
        <a href="/" class="logo">
          <img src="{% static 'projects/transgigabot.gif' %}" />ACMxLabs
        </a>
        <div class="copyright">
          <a href="https://github.com/ColoradoSchoolOfMines"><i class="fa fa-github fa-2x"></i>&nbsp;</a>
          <a href="https://twitter.com/acmxlabs"><i class="fa fa-twitter fa-2x"></i>&nbsp;</a>
          &copy; 2014 ACMx. All rights reserved.
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <form class="well" method="post" action="{% url 'account_logout' %}">
          <div class="modal-header">
            <h3>Are you sure you want to log out?</h3>
          </div>
          <div class="modal-body">
            {% csrf_token %}
          </div>
          <div class="modal-footer">
            <input class="btn btn-primary" type="submit" value="Log Out" />
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

  <!-- js -->
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="https://bootflat.github.io/bootflat/js/icheck.min.js"></script>
  <script src="{% static 'projects/jquery.js' %}" async="false" defer="true"></script>
  <script>
    $(document).ready(function() {
        $('a').tooltip();
    });
  </script>
</body>
</html>

projects/templates/projects/contact.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% block title %}Contact | ACMx Labs{% endblock %}

{% block content %}
    <div class="slider">
      <div class="welcome">
       <div class="container-fluid">
          <div class="row">
            <div class="col-md-offset-2 col-md-5">
              <h1>Contact us!</h1>
            </div>

            <div class="col-md-3">
              <p><strong>President:</strong>&nbsp;<a href="mailto:shamrick@mymail.mines.edu">Steve Hamrick</a></p>
              <p><strong>Vice President:</strong>&nbsp;<a href="mailto:vkadiris@mymail.mines.edu">Vishnu Kadirisani</a></p>
              <p><strong>Secretary:</strong>&nbsp;<a href="mailto:nttran@mymail.mines.edu">Nhan Tran</a></p>
              <p><strong>Treasurer:</strong>&nbsp;<a href="mailto:achampio@mymail.mines.edu">Alan Champion</a></p>
            </div>
          </div><br>
          <div class="row">
            <div class="col-md-offset-2 col-md-8">
            <p>Come to our meeting, BB 316A at 6pm every Tuesday</p><br>
            <p>Click <a href="https://mailman.mines.edu/mailman/listinfo/acmx">here</a> to join our Mailing List!</p><br>
            <a href="https://github.com/ColoradoSchoolOfMines"><i class="fa fa-github fa-4x"></i>&nbsp;GitHub</a><br><br>
            <a href="https://trello.com/acmx"><i class="fa fa-trello fa-4x"></i>&nbsp; Trello</a><br><br>
            <a href="https://twitter.com/acmxlabs"><i class="fa fa-twitter fa-4x"></i>&nbsp; Twitter</a><br><br>
           <a href="https://orgsync.com/66700/chapter"><i class="fa fa-orgsync fa-4x"></i>&nbsp; OrgSync</a><br><br>
           </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

projects/templates/projects/index.html
{% extends "projects/base.html" %}
{% load staticfiles %}
{% block title %}ACMx Labs{% endblock %}
{% block content %}
    <div class="slider">
        <div class="welcome">
            <div class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
                <div class="row">
                    <div class="col-mid-8" style="padding-bottom: 200px">
                        <h1> Welcome to ACMx!</h1>
                        <h3>Make something epic. Share it.</h3>
                        <p>We are the Association for Computing Machinery group on campus at the Colorado School of Mines.</p>
                        <p>We are a group of creators with a heavy focus on real-life projects that are relevant to both students and industry alike. We work with all disciplines, with members from electrical, petroleum, physics, and computer engineering.</p>
                        <p>We do elementary outreach to increase interest in our craft, as well as regularly compete in code competitions to sharpen it. Our projects range from wireless mesh parking sensor networks to remote tele-presence robots. Sign in to add your own projects!</p>
                        <h4>We are what we create. What else is there?</h4><br>
                       <p><b>Meetings:</b> every Tuesday at 6pm in BB 316A</b><br><br>
                        <p>Our current projects:</p>
                        <div id="accordion">
                            {% for project in project_list %}
                                <hgroup>
                                    <h3>{{ project.title }}</h3>
                                    <h5>{{ project.description }}</h5>
                                </hgroup>
                                <div>
                                    <a href="{% url 'projects:detail' project.slug %}"><p>View project page</p></a>
                                    <p>Primary Languages Used: {{ project.languages }}</p>
                                    <p>Contributors: {{ project.contributors }}</p>
                                    <p>GitHub link(s): {{ project.link }}</p>
                                </div>
                            {% empty %}
                            <p>No projects have been added yet! Add a new one!</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--<script src="{% static 'projects/parallax.js' %}"></script>-->
{% endblock %}
/

projects/templates/projects/project.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% block title %}{{ project.title }}{% endblock %}

{% block content %}
    <div class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      <div class="row">
        <div class="project-content">
          <h1>{{ project.title }}</h1>
          {{ details|safe }}
          <img src="/media/{{ project.image }}" /><br>
          <h5>GitHub Link: {{ project.link }}</h5>
          <h5>Contributors: {{ project.contributors }}</h5>
          <h5>Primary Languages Used: {{ project.languages }}</h5>
        </div>
      </div>
      <div class="spacer"></div>
    </div>
{% endblock %}

projects/templates/projects/project_create.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% block extra_includes %}
    <link rel="stylesheet" href="{% static 'projects/editor.css' %}"/>
    <script type="text/javascript" src="{% static 'projects/editor.js' %}"></script>
    <script type="text/javascript" src="{% static 'projects/marked.js' %}"></script>
{% endblock %}

{% block title %}New Project | ACMx Labs{% endblock %}

{% block content %}
    <div id="page_content" class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2" style="margin-bottom:100px;">
        <!-- TODO: Move that margin outta here. -->
        <h3>Create a new project!</h3>
        {{ form.errors }}
        <form enctype="multipart/form-data" action="{{ action }}" method="POST" role="form">
            {% csrf_token %}
            <div id="project_create">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" value="{{ title }}"
                           class="form-control" placeholder="Enter project name">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <input type="text" name="description" id="description" value="{{ description }}"
                           class="form-control" placeholder="Enter a short description">
                </div>
                <div class="form-group">
                    <label for="long_description">Details</label>
                    <textarea name="long_description" id="long_description">{{ long_description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="link">Link</label>
                    <input type="text" name="link" id="link" value="{{ link }}"
                           class="form-control" placeholder="Enter the main link">
                </div>
                <div class="form-group">
                    <label for="contributors">Contributors</label>
                    <input type="text" name="contributors" id="contributors" value="{{ project.contributors }}"
                           class="form-control" placeholder="Enter the contributors">
                </div>
                <div class="form-group">
                    <label for="languages">Languages</label>
                    <input type="text" name="languages" id="languages" value="{{ project.languages }}"
                           class="form-control" placeholder="Enter the primary languages used">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" name="image" id="image" placeholder="Upload an image">
                </div>
                <input type="submit" name="submit" class="btn btn-default" value="Create">
            </div>
        </form>

        <script>
        var editor = new Editor();
        editor.render();
        </script>
    </div>
{% endblock %}

projects/templates/projects/project_edit.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% block extra_includes %}
    <link rel="stylesheet" href="{% static 'projects/editor.css' %}"/>
    <script type="text/javascript" src="{% static 'projects/editor.js' %}"></script>
    <script type="text/javascript" src="{% static 'projects/marked.js' %}"></script>
{% endblock %}

{% block title %}Edit {{ project.title }} | ACMx Labs{% endblock %}

{% block content %}
    <div id="page_content" class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2" style="margin-bottom:100px;">

        <form action="{{ action }}" method="POST" role="form">
            {% csrf_token %}
            <div id="project_create">
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" value="{{ project.title }}"
                           class="form-control" placeholder="Enter project name">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <input type="text" name="description" id="description" value="{{ project.description }}"
                           class="form-control" placeholder="Enter a short description">
                </div>
                <div class="form-group">
                    <label for="long_description">Details</label>
                    <textarea name="long_description" id="long_description">{{ project.long_description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="link">Link</label>
                    <input type="text" name="link" id="link" value="{{ project.link }}"
                           class="form-control" placeholder="Enter the main link">
                </div>
                <div class="form-group">
                    <label for="contributors">Contributors</label>
                    <input type="text" name="contributors" id="contributors" value="{{ project.contributors }}"
                           class="form-control" placeholder="Enter the contributors">
                </div>
                <div class="form-group">
                    <label for="languages">Languages</label>
                    <input type="text" name="languages" id="languages" value="{{ project.languages }}"
                           class="form-control" placeholder="Enter the primary languages used">
                </div>
                <input type="submit" name="submit" class="btn btn-default" value="Save">
            </div>
        </form>

        <script>
        var editor = new Editor();
        editor.render();
        </script>
    </div>
{% endblock %}

projects/templates/projects/support.html
{% extends "projects/base.html" %}
{% load staticfiles %}

{% block title %}Support Us! | ACMx Labs{% endblock %}

{% block content %}
    <div>
        Hi from support.html!
    </div>
{% endblock %}

projects/templates/projects/user_list.html
{% extends "projects/base.html" %}

{% block title %}Users | ACMx Labs{% endblock %}

{% block content %}
    {% for user in user_list %}
        <!-- Link to custom user pages. Use AJAX stuff to avoid having to define more urls in Django -->
        <a href="{% url 'projects:user_profile' user.user.username %}">{{ user }}</a>
        <a href="{% url 'projects:user_profile_edit' user.user.username %}">[EDIT]</a>
        <br>
    {% endfor %}
{% endblock %}